---
title: "Désordres nutritionnels"
---

# Objectif

Le diagnostic et l'observation de carences permettent d'appréhender l'état nutritionnel de la vigne. Une carence (ou un excès) d'éléments nutritifs peut fausser l'évaluation d'un essai en affectant la vigueur et la sensibilité de la vigne aux maladies.

Si un désordre nutritionnel est détectée en cours d'essai, des ajustements doivent être envisagés pour garantir la robustesse des résultats (élimination des ceps malades de l'échantillon observé, fertilisation ou mesure corrective...).

# Principe de la mesure

La vigne a besoin d'éléments minéraux variés pour assurer sa croissance tout au long de son cycle de développement. Il n'est pas rare d'être confronté sur le terrain à des plantes souffrant de carences ou d'excès d'éléments nutritifs. Ces désordres se manifestent assez fréquemment sur vigne par des décolorations et des déformations surtout foliaires, de nature et de répartition variables sur les plantes [@blancard].

La mesure se base donc sur des observations visuelles régulières sur la vigne, en notant la présence et la gravité des symptômes de désordres nutritionnels.

# Méthode de mesure

## Échantillonnage

### Nombre d'observations

L'observation se fait le long d'un parcours, à l'échelle de la parcelle ou de la modalité.

### Ceps à observer

-   Prendre des ceps représentatifs de la parcelle (ou les ceps qui sont observés par ailleurs)
-   Laisser quelques ceps en bordure de rangs.

### Organes à observer

Feuilles et grappes en particulier, à adapter selon la carence.

## Mesure

### Réalisation

L'opérateur place la parcelle dans la catégorie correspondante pour les feuilles et pour les grappes en ce qui concerne :

-   la fréquence de ceps touchés,
-   la fréquence d’organes touchés,
-   l'intensité[^1] moyenne des symptômes (comprenant les organes sains).

[^1]: L’*intensité* est l'impact global des symptômes de la maladie sur le feuillage et sur les grappes dans leur ensemble. Par exemple, si 50% des feuilles d’un cep sont touchées , avec une intensité moyenne sur feuilles touchées de 25%, l'intensité globale de symptômes sur le cep sera de 50\*25/100 = 12,5%.

| Fréquence de ceps touchés | Fréquence d'organes touchés | Intensité globale des symptômes |
|----|----|----|
| 5 - Présence généralisée (\>80%) | 5 - Très élevée (\>50%) | 5 - Dégâts très importants (\>50%) |
| 4 - Présence très importante (50 - 80%) | 4 - Elevée (10-50%) | 4 - Dégâts importants (10- 50%) |
| 3 - Présence importante (25- 50%) | 3 - Moyenne ( 5 - 10%) | 3 - Dégâts significatifs (5-10%) |
| 2 - Présence régulière (5 - 25%) | 2 - Faible (1 - 5%) | 2 - Facilement visibles (1-5%) |
| 1 - Rares (\<5%) | 1 - Cas isolés (\<1%) | 1 - Traces (\<1%) |
| 0 - Nulle | 0 - Nulle | 0 - Nulle |

: Echelle de notation, protocole simplifié OSCAR [@delière2023]

::: callout-note
Ne pas oublier de noter aussi le nom de l'observateur, la date d'observation et le stade phénologique. Compléter la notation par la prise de photos pour valider le diagnostic.
:::

::: callout-warning
Une analyse de laboratoire avec dosage des teneurs en éléments minéraux dans les pétioles ou feuilles peut-être utile pour confirmer une carence. Les analyses de sol peuvent aussi permettre d'affiner le diagnostic et de calibrer les mesures correctives.

Attention aux risques de confusion avec d'autres symptômes (maladies, sécheresse...) !
:::

### Outils

Feuille de notation.

### Période de mesure

La période d'observation dépend du type de carence.

| Carences             | Période d'observation |
|----------------------|-----------------------|
| Chlorose ferrique    | Printemps / Floraison |
| Carence en potassium | Eté                   |
| Carence en magnésium | Eté                   |
| Carence en potassium | Eté                   |

: Périodes d'observations selon les principales carences

### Aspects pratiques

# Traitement des résultats

## Définition des variables

Moyenne par modalité ou par parcelle.

## Interprétation des résultats

L'interprétation des résultats doit tenir compte de l'historique de fertilisation sur la parcelle, du matériel végétal (cépage et porte-greffe), de l'historique météo (les printemps pluvieux favorisent la chlorose ferrique).

# Compléments d'information

## Ressources complémentaires

Fiche sur la [chlorose ferrique](https://www.vignevin-occitanie.com/fiches-pratiques/la-chlorose-ferrique/)

[Plateforme ephytia](https://ephytia.inra.fr/fr/C/7070/Vigne-Desordres-nutritionnels) pour aide à la reconnaissance des symptômes de désordres nutritionnels sur vigne.

## Références
