---
title: "Observations oïdium - Méthode EPPO"
---

# Objectif

Les observations de maladies, en particulier mildiou et oïdium (principales maladies cryptogamiques de la vigne) permettent d'évaluer l'efficacité des stratégies de protection, comprendre la dynamique des maladies, ou encore caractériser la sensibilité variétale...

# Principe de la mesure

Les observations visuelles sont réalisées régulièrement en notant la présence et la sévérité des symptômes de maladies. La méthode de mesure présentée dans cette fiche est décrite dans @ceb_oidium et @eppo2001.

::: callout-important
L'évaluation visuelle de la proportion de baies ou de surface atteinte par la maladie repose sur une interprétation humaine et peut varier fortement d'un observateur à l'autre. Il est nécessaire :

-   de s'entraîner au préalable, au champ et avec des échelles calibrées
-   de contrôler le facteur observateur dans la réalisation des notations, par exemple réalisant toutes les notations d'un bloc par le même observateur.
:::

{{< pagebreak >}}

# Réalisation de la mesure sur le terrain

## Échantillonnage

### Nombre d'observations

Sur feuilles, observer 100 feuilles pour chaque répétition.

Sur grappes, observer 50 (essai en conditions contrôlées) à 100 grappes (essai en conditions naturelles) pour chaque répétition.

### Ceps à observer

-   Prendre des ceps représentatifs de la parcelle (ou les ceps qui sont observés par ailleurs)
-   Laisser quelques ceps en bordure de rangs.

### Organes à observer

Feuilles et grappes de chaque cep.

## Mesure

### Réalisation

Sur chaque feuille ou grappe échantillonnée aléatoirement, la proportion de feuille ou de baies atteinte par la maladie est estimée visuellement.

![Echelle d'évaluation de la surface atteinte sur grappe [@scott2020].](images/echelle_maladie_grappe.jpg){width="370"}

::: callout-note
Ne pas oublier de noter aussi le nom de l'observateur, la date d'observation et le stade phénologique.
:::

### Outils

Feuille de notation.

Certaines applications existent pour la saisie terrain sur smartphone, comme par exempe [PMapp](https://www.vineyardteam.org/files/resources/PMapp.pdf) .


### Période de mesure

Les comptages précis peuvent être réalisés à tout moment, en fonction de l'évolution de l'épidémie maladie et à partir d'un seuil minimal d'attaque.

Sur feuilles, une à deux observations en cours de saison suivant la pression maladie.

Les grappes sont les plus sensibles à la maladie. L'évolution de la maladie s'observe facilement entre la nouaison et le début de la véraison. Au-delà, surtout sur les cépages rouges, il est impossible d'apprécier correctement les dégâts. Une dernière observation peut être réalisée avant récolte.

| Organes | 7-8 feuilles étalées | Nouaison (BBCH71) | Fermeture de la grappe (BBCH77) | Début véraison (BBCH81) |
|---------------|---------------|---------------|---------------|---------------|
| Rameaux | drapeaux si cépage ou parcelle très sensible |  |  |  |
| Feuilles |  | suivant pression maladies | recommandé |  |
| Grappes |  |  | recommandé | recommandé |

### Aspects pratiques

La notation est assez rapide, environ 5 minutes sont nécessaires à deux personnes (un observateur entraîné et un notateur) pour observer 100 feuilles ou 50 grappes.

{{< pagebreak >}}

# Traitement des résultats

## Définition des variables

La sévérité S (*severity* en anglais) est la surface de feuille ou de grappes attaquée par la maladie, exprimée en pourcentage de la surface totale [@nutterjr1991], sur :

-   feuille ([UN_LEAF_PC](https://cropontology.org/term/CO_356:1000221))
-   grappe ([UN_BER_PC](https://cropontology.org/term/CO_356:1000176)).

A partir des valeurs de sévérité, il est possible de calculer :

-   La fréquence F (*incidence* en anglais) : nombre de feuilles ou de grappes présentant des symptômes de maladies exprimé en pourcentage du nombre total de feuilles ou de grappes observées.
-   L'intensité d'attaque I (*intensity* en anglais) : moyenne des sévérités observées sur l'ensemble des grappes ou feuilles observées.

## Interprétation des résultats

L'interprétation des résultats doit tenir compte de la pression locale de maladie (qui dépend en grande partie de l'historique météorologique) et de l'itinéraire technique de protection phytosanitaire sur la parcelle.

# Compléments d'information

## Ressources complémentaires

[Plateforme ephytia](https://ephytia.inra.fr/fr/P/97/Vigne) pour aide à la reconnaissance des symptômes de maladie sur vigne.

## Références
