---
title: "Introduction"
format:  html
---

Ce site recense des fiches méthodologiques pour la collecte de données dans un cadre d'expérimentation en vigne et vin. L'objectif est de partager des méthodes reconnues et validées par la communauté scientifique vigne et vin, de façon ouverte et collaborative.

# Description des fiches

Chaque fiche est dédiée à une mesure ou observation avec des explications sur la réalisation sur le terrain et sur le traitement des résultats.


Chaque mesure ou observation génère des variables qui sont décrites dans les fiches. Le cas échéant, chaque variable est alignée avec le [référentiel CO_356](ref_co356.qmd) [@duchene2019]. 
Le nom préféré de la variable est indiqué en gras avec entre parenthèse son identifiant. 


L'utilisation d'un référentiel commun est recommandé pour faciliter l'interopérabilité des données.

::: callout-tip
Toutes les fiches sont consultables en ligne et téléchargeables en format docx, modifiables librement sous licence [CC-BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/).
:::

# Comment contribuer ?

## Proposer des révisions sur une fiche existante

Malgré nos efforts, ces fiches peuvent sans doute être améliorées. Si vous souhaitez proposer des révisions (corrections, ajouts, modification), le plus simple est de télécharger la fiche concernée en format docx, de l'ouvrir et de l'éditer en mode révision.

Vous pouvez nous la renvoyer par email (voir rubrique [A propos](about.qmd)) en l'accompagnant de quelques explications sur les révisions proposées.

Après une phase de validation et d'échange, la fiche sera mise à jour et votre nom sera ajouté (avec votre accord) à la liste des contributeurs.

## Proposer une nouvelle fiche

Si vous souhaitez proposer une nouvelle fiche méthodologique, un [modèle vierge](template_fiche.docx) est disponible au format docx. Vous pouvez l'éditer et nous envoyer votre proposition par email (voir rubrique [A propos](about.qmd)) en l'accompagnant de quelques explications.

Si vous n'avez pas le temps, nous pouvons prendre en charge la rédaction.

::: callout-caution
Il est toutefois recommandé de prendre contact avec nous au préalable, d'une part pour vérifier qu'une fiche équivalente n'est pas en préparation, et d'autre part pour identifier des experts pour appui à la rédaction ou relecture.
:::

# Ressources complémentaires

-   [Centre de ressources viti-oeno](https://vitioeno.mistea.inrae.fr/resource/app/) : un site web qui recense des documents, applications, référentiels (variables et matériel végétal) à destination des expérimentateurs de la filière vigne et vin.
-   [Guide pour la description d’une expérimentation en vigne](https://vignevin.github.io/standard_guide/) : un guide pour décrire une expérimentation en viticulture.

# Références
